spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://memo-mysql.c1ko8y4e4uag.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: root
    password: lkcc0411!
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7fe1ea9a36e18292e75a035b08876a9a
            client-secret: 6bG35etxsDkS0M2Us5JxDQXerFZJ3imd
#            redirect-uri: "http://localhost:3000/auth"
            redirect-uri: "http://localhost:3000/auth"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          scope:
            - profile_nickname
            - profile_image
            - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



secret-key: ThisStatementIsJwtSecretKeyDoNotUseThisStatement;